### ISSUE TITLE
Checkboxes not highlighted

### ISSUE THREAD

**Issue by mschoe** [bpmn-io/bpmn-properties-panel#187]
__Describe the Bug__

Checkboxes are not highlighted when navigate via keyboard (tab-key)

__Steps to Reproduce__

1. use the tab key to select the Asynchronous Continuation After checkbox

__Expected Behavior__

checkbox elements are highlighted 

__Environment__

- Modeler 4.11.1-new-properties-panel
- OS: Linux Mint 20.2 Cinnamon

**Comment by andreasgeier** [comment]
We plan to provide a unified style and behavior for all form elements within the Modeler (and this considers keyboard navigation), but we are not able to implement it in this quarter.

I think we should provide a quick fix here.

**Comment by pinussilvestrus** [comment]
We use the native checkbox here, without custom styling. What I could think about is to add a minimal outline as default style

![Kapture 2021-11-19 at 15 19 05](https://user-images.githubusercontent.com/9433996/142637514-fc107659-3aa6-4163-a9b3-919e64544217.gif)

```css
.bio-properties-panel-input[type="checkbox"]:focus {
  outline: 1px solid var(--input-focus-border-color);
  outline-offset: 0;
}
```
