### ISSUE TITLE
Consistently use sentence case for labels and (group) titles

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-properties-panel#81]
__What should we do?__

We currently have the problem that we don't use **sentence case** in all property labels and group titles.

![image](https://user-images.githubusercontent.com/9433996/130935174-27bdcb89-f4c3-4b17-946e-d2e97cff249e.png)

![image](https://user-images.githubusercontent.com/9433996/130935278-133c724d-c61b-4f38-a5fc-aba3d87e8cc0.png)

One edge case would be the term "ID" where we actively want to have the capitalized letters. 

We could

a) update all existing group titles and labels manually
b) create a general css rule in `@bpmn-io/properties-panel`, something like

```css
.bio-properties-panel-label {
  text-transform: lowercase;
}

.bio-properties-panel-label::first-letter {
  text-transform: uppercase;
}
```

__Why should we do it?__

It's part of our latest [technical writing guidelines.](https://docs.google.com/document/d/1Tcw1GSemSFFSXZDlfGEygvW4RHPInQnC4cLuAQXlQ6U/edit#)
